[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-Ctarget-feature=+crt-static", "-Clink-arg=-T../user.ld"]
linker = "/home/hyperb0rean/Documents/itmo_os/sc-dt/riscv-gcc/riscv64-unknown-elf/bin/ld"